image: docker:latest

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay
  IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  IMAGE_LATEST: $CI_REGISTRY_IMAGE:latest

services:
- docker:dind

stages:
  - build
  - test
  - cleanup
  - deploy

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME

test:
  stage: test
  script:
    - docker pull $IMAGE_NAME
    - docker run -v `pwd`:/git $IMAGE_NAME /bin/sh -c "wget -qO- https://fedoraproject.org/static/hotspot.txt | grep OK && cd /git && hugo"

deploy:
  stage: deploy
  script:
    - docker pull $IMAGE_NAME
    - docker tag $IMAGE_NAME $IMAGE_LATEST
    - docker push $IMAGE_LATEST
  only:
    - tags
